/**
 * generated by Xtext
 */
package com.rogueai.janki.card.lang.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#quickfixes
 */
@SuppressWarnings("all")
public class CardTemplateQuickfixProvider extends DefaultQuickfixProvider {
}
