/*
 * generated by Xtext
 */
package com.rogueai.janki.card.lang.validation

import org.eclipse.xtext.validation.Check
import com.rogueai.janki.card.lang.cardTemplate.Tag
import com.rogueai.janki.card.lang.cardTemplate.CardTemplatePackage

//import org.eclipse.xtext.validation.Check
/**
 * Custom validation rules. 
 *
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 * 
 * @author matsu
 */
class CardTemplateValidator extends AbstractCardTemplateValidator {

	public static val INVALID_NAME = 'invalidEndTagName'

	/**
	 * Checks for a valid <code>end tag name</code>, e.g.:
	 * <pre>
	 * &lt;a>&lt;/a> - valid
	 * &lt;a>&lt;/A> - valid
	 * </pre>
	 * TODO: validate correctly inline end tag, e.g.: <code>&lt;a /></code> 
	 */
	@Check
	def checkEndTagName(Tag tag) {
		if (tag.endTagName != null) {
			if (!tag.endTagName.equalsIgnoreCase(tag.startTagName)) {
				error('End tag name must match start tag name',
					CardTemplatePackage.Literals.TAG__END_TAG_NAME, INVALID_NAME)
			}
		}
	}
}
