package com.rogueai.janki.core.persistence.jpa.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Col generated by hbm2java
 */
@Entity
@Table(name = "col")
public class Collection implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6309683182291502241L;
	
	private Integer id;
	private int crt;
	private int mod;
	private int scm;
	private int ver;
	private int dty;
	private int usn;
	private int ls;
	private String conf;
	private String models;
	private String decks;
	private String dconf;
	private String tags;

	public Collection() {
	}

	public Collection(Integer id, int crt, int mod, int scm, int ver, int dty, int usn, int ls, String conf, String models, String decks, String dconf,
			String tags) {
		this.id = id;
		this.crt = crt;
		this.mod = mod;
		this.scm = scm;
		this.ver = ver;
		this.dty = dty;
		this.usn = usn;
		this.ls = ls;
		this.conf = conf;
		this.models = models;
		this.decks = decks;
		this.dconf = dconf;
		this.tags = tags;
	}

	@Id
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "crt", nullable = false)
	public int getCrt() {
		return this.crt;
	}

	public void setCrt(int crt) {
		this.crt = crt;
	}

	@Column(name = "mod", nullable = false)
	public int getMod() {
		return this.mod;
	}

	public void setMod(int mod) {
		this.mod = mod;
	}

	@Column(name = "scm", nullable = false)
	public int getScm() {
		return this.scm;
	}

	public void setScm(int scm) {
		this.scm = scm;
	}

	@Column(name = "ver", nullable = false)
	public int getVer() {
		return this.ver;
	}

	public void setVer(int ver) {
		this.ver = ver;
	}

	@Column(name = "dty", nullable = false)
	public int getDty() {
		return this.dty;
	}

	public void setDty(int dty) {
		this.dty = dty;
	}

	@Column(name = "usn", nullable = false)
	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	@Column(name = "ls", nullable = false)
	public int getLs() {
		return this.ls;
	}

	public void setLs(int ls) {
		this.ls = ls;
	}

	@Column(name = "conf", nullable = false, length = 2000000000)
	public String getConf() {
		return this.conf;
	}

	public void setConf(String conf) {
		this.conf = conf;
	}

	@Column(name = "models", nullable = false, length = 2000000000)
	public String getModels() {
		return this.models;
	}

	public void setModels(String models) {
		this.models = models;
	}

	@Column(name = "decks", nullable = false, length = 2000000000)
	public String getDecks() {
		return this.decks;
	}

	public void setDecks(String decks) {
		this.decks = decks;
	}

	@Column(name = "dconf", nullable = false, length = 2000000000)
	public String getDconf() {
		return this.dconf;
	}

	public void setDconf(String dconf) {
		this.dconf = dconf;
	}

	@Column(name = "tags", nullable = false, length = 2000000000)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

}
