package com.rogueai.janki.core.persistence.jpa.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Graves generated by hbm2java
 */
@Entity
@Table(name = "graves")
public class Grave implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3919332543347555802L;

	private GraveId id;

	public Grave() {
	}

	public Grave(GraveId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "usn", column = @Column(name = "usn", nullable = false)),
			@AttributeOverride(name = "oid", column = @Column(name = "oid", nullable = false)),
			@AttributeOverride(name = "type", column = @Column(name = "type", nullable = false)) })
	public GraveId getId() {
		return this.id;
	}

	public void setId(GraveId id) {
		this.id = id;
	}

}
