package com.rogueai.janki.core.persistence.jpa.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GravesId generated by hbm2java
 */
@Embeddable
public class GraveId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2756264318548111894L;

	private int usn;
	private int oid;
	private int type;

	public GraveId() {
	}

	public GraveId(int usn, int oid, int type) {
		this.usn = usn;
		this.oid = oid;
		this.type = type;
	}

	@Column(name = "usn", nullable = false)
	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	@Column(name = "oid", nullable = false)
	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GraveId))
			return false;
		GraveId castOther = (GraveId) other;

		return (this.getUsn() == castOther.getUsn()) && (this.getOid() == castOther.getOid()) && (this.getType() == castOther.getType());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUsn();
		result = 37 * result + this.getOid();
		result = 37 * result + this.getType();
		return result;
	}

}
