package com.rogueai.janki.core.persistence.jpa.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Notes generated by hbm2java
 */
@Entity
@Table(name = "notes")
public class Note implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -879862390350391665L;

	private Integer id;
	private String guid;
	private int mid;
	private int mod;
	private int usn;
	private String tags;
	private String flds;
	private int sfld;
	private int csum;
	private int flags;
	private String data;

	public Note() {
	}

	public Note(Integer id, String guid, int mid, int mod, int usn, String tags, String flds, int sfld, int csum, int flags, String data) {
		this.id = id;
		this.guid = guid;
		this.mid = mid;
		this.mod = mod;
		this.usn = usn;
		this.tags = tags;
		this.flds = flds;
		this.sfld = sfld;
		this.csum = csum;
		this.flags = flags;
		this.data = data;
	}

	@Id
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "guid", nullable = false, length = 2000000000)
	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	@Column(name = "mid", nullable = false)
	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	@Column(name = "mod", nullable = false)
	public int getMod() {
		return this.mod;
	}

	public void setMod(int mod) {
		this.mod = mod;
	}

	@Column(name = "usn", nullable = false)
	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	@Column(name = "tags", nullable = false, length = 2000000000)
	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	@Column(name = "flds", nullable = false, length = 2000000000)
	public String getFlds() {
		return this.flds;
	}

	public void setFlds(String flds) {
		this.flds = flds;
	}

	@Column(name = "sfld", nullable = false)
	public int getSfld() {
		return this.sfld;
	}

	public void setSfld(int sfld) {
		this.sfld = sfld;
	}

	@Column(name = "csum", nullable = false)
	public int getCsum() {
		return this.csum;
	}

	public void setCsum(int csum) {
		this.csum = csum;
	}

	@Column(name = "flags", nullable = false)
	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	@Column(name = "data", nullable = false, length = 2000000000)
	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
