package com.rogueai.janki.core.persistence.jpa.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Revlog generated by hbm2java
 */
@Entity
@Table(name = "revlog")
public class Revlog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7356679516107573007L;

	private Integer id;
	private int cid;
	private int usn;
	private int ease;
	private int ivl;
	private int lastIvl;
	private int factor;
	private int time;
	private int type;

	public Revlog() {
	}

	public Revlog(Integer id, int cid, int usn, int ease, int ivl, int lastIvl, int factor, int time, int type) {
		this.id = id;
		this.cid = cid;
		this.usn = usn;
		this.ease = ease;
		this.ivl = ivl;
		this.lastIvl = lastIvl;
		this.factor = factor;
		this.time = time;
		this.type = type;
	}

	@Id
	@Column(name = "id")
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "cid", nullable = false)
	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	@Column(name = "usn", nullable = false)
	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	@Column(name = "ease", nullable = false)
	public int getEase() {
		return this.ease;
	}

	public void setEase(int ease) {
		this.ease = ease;
	}

	@Column(name = "ivl", nullable = false)
	public int getIvl() {
		return this.ivl;
	}

	public void setIvl(int ivl) {
		this.ivl = ivl;
	}

	@Column(name = "lastIvl", nullable = false)
	public int getLastIvl() {
		return this.lastIvl;
	}

	public void setLastIvl(int lastIvl) {
		this.lastIvl = lastIvl;
	}

	@Column(name = "factor", nullable = false)
	public int getFactor() {
		return this.factor;
	}

	public void setFactor(int factor) {
		this.factor = factor;
	}

	@Column(name = "time", nullable = false)
	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
