package com.rogueai.janki.core.persistence.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import com.rogueai.janki.core.persistence.dao.impl.NoteDao;

/**
 * Notes generated by hbm2java
 */
@DatabaseTable(tableName = "notes", daoClass = NoteDao.class)
public class Note implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@DatabaseField(columnName = "id", id = true)
	private Integer id;

	@DatabaseField(columnName = "guid", canBeNull = false, width = 2000000000)
	private String guid;

	@DatabaseField(columnName = "mid", canBeNull = false)
	private int mid;

	@DatabaseField(columnName = "mod", canBeNull = false)
	private int mod;

	@DatabaseField(columnName = "usn", canBeNull = false)
	private int usn;

	@DatabaseField(columnName = "tags", canBeNull = false, width = 2000000000)
	private String tags;

	@DatabaseField(columnName = "flds", canBeNull = false, width = 2000000000)
	private String flds;

	@DatabaseField(columnName = "sfld", canBeNull = false)
	private int sfld;

	@DatabaseField(columnName = "csum", canBeNull = false)
	private int csum;

	@DatabaseField(columnName = "flags", canBeNull = false)
	private int flags;

	@DatabaseField(columnName = "data", canBeNull = false, width = 2000000000)
	private String data;

	public Note() {
	}

	public Note(Integer id, String guid, int mid, int mod, int usn, String tags, String flds, int sfld, int csum, int flags, String data) {
		this.id = id;
		this.guid = guid;
		this.mid = mid;
		this.mod = mod;
		this.usn = usn;
		this.tags = tags;
		this.flds = flds;
		this.sfld = sfld;
		this.csum = csum;
		this.flags = flags;
		this.data = data;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getGuid() {
		return this.guid;
	}

	public void setGuid(String guid) {
		this.guid = guid;
	}

	public int getMid() {
		return this.mid;
	}

	public void setMid(int mid) {
		this.mid = mid;
	}

	public int getMod() {
		return this.mod;
	}

	public void setMod(int mod) {
		this.mod = mod;
	}

	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

	public String getFlds() {
		return this.flds;
	}

	public void setFlds(String flds) {
		this.flds = flds;
	}

	public int getSfld() {
		return this.sfld;
	}

	public void setSfld(int sfld) {
		this.sfld = sfld;
	}

	public int getCsum() {
		return this.csum;
	}

	public void setCsum(int csum) {
		this.csum = csum;
	}

	public int getFlags() {
		return this.flags;
	}

	public void setFlags(int flags) {
		this.flags = flags;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

}
