package com.rogueai.janki.core.persistence.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import com.rogueai.janki.core.persistence.dao.impl.RevlogDao;

/**
 * Revlog generated by hbm2java
 */
@DatabaseTable(tableName = "revlog", daoClass = RevlogDao.class)
public class Revlog implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@DatabaseField(columnName = "id")
	private Integer id;

	@DatabaseField(columnName = "cid", canBeNull = false)
	private int cid;

	@DatabaseField(columnName = "usn", canBeNull = false)
	private int usn;

	@DatabaseField(columnName = "ease", canBeNull = false)
	private int ease;

	@DatabaseField(columnName = "ivl", canBeNull = false)
	private int ivl;

	@DatabaseField(columnName = "lastIvl", canBeNull = false)
	private int lastIvl;

	@DatabaseField(columnName = "factor", canBeNull = false)
	private int factor;

	@DatabaseField(columnName = "time", canBeNull = false)
	private int time;

	@DatabaseField(columnName = "type", canBeNull = false)
	private int type;

	public Revlog() {
	}

	public Revlog(Integer id, int cid, int usn, int ease, int ivl, int lastIvl, int factor, int time, int type) {
		this.id = id;
		this.cid = cid;
		this.usn = usn;
		this.ease = ease;
		this.ivl = ivl;
		this.lastIvl = lastIvl;
		this.factor = factor;
		this.time = time;
		this.type = type;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCid() {
		return this.cid;
	}

	public void setCid(int cid) {
		this.cid = cid;
	}

	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	public int getEase() {
		return this.ease;
	}

	public void setEase(int ease) {
		this.ease = ease;
	}

	public int getIvl() {
		return this.ivl;
	}

	public void setIvl(int ivl) {
		this.ivl = ivl;
	}

	public int getLastIvl() {
		return this.lastIvl;
	}

	public void setLastIvl(int lastIvl) {
		this.lastIvl = lastIvl;
	}

	public int getFactor() {
		return this.factor;
	}

	public void setFactor(int factor) {
		this.factor = factor;
	}

	public int getTime() {
		return this.time;
	}

	public void setTime(int time) {
		this.time = time;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
