/**
 * generated by Xtext
 */
package com.rogueai.janki.card.lang.ui.contentassist;

import com.rogueai.janki.card.lang.ui.contentassist.AbstractCardTemplateProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class CardTemplateProposalProvider extends AbstractCardTemplateProposalProvider {
}
