/*
* generated by Xtext
*/
package com.rogueai.janki.card.lang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CardTemplateUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.rogueai.janki.card.lang.ui.internal.CardTemplateActivator.getInstance().getInjector("com.rogueai.janki.card.lang.CardTemplate");
	}
	
}
