/*
 * generated by Xtext
 */
package com.rogueai.janki.card.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CardTemplateUiModule extends com.rogueai.janki.card.lang.ui.AbstractCardTemplateUiModule {
	public CardTemplateUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
