/*
 * generated by Xtext
 */
package com.rogueai.janki.card.lang.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractCardTemplateValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.rogueai.janki.card.lang.cardTemplate.CardTemplatePackage.eINSTANCE);
		return result;
	}
}
