package com.rogueai.janki.core.persistence.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import java.util.Map;

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import com.rogueai.janki.core.persistence.dao.impl.CollectionDao;

/**
 * Col generated by hbm2java
 */
@DatabaseTable(tableName = "col", daoClass = CollectionDao.class)
public class Collection implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@DatabaseField(columnName = "id")
	private Integer id;

	@DatabaseField(columnName = "crt", canBeNull = false)
	private int crt;

	@DatabaseField(columnName = "mod", canBeNull = false)
	private int mod;

	@DatabaseField(columnName = "scm", canBeNull = false)
	private int scm;

	@DatabaseField(columnName = "ver", canBeNull = false)
	private int ver;

	@DatabaseField(columnName = "dty", canBeNull = false)
	private int dty;

	@DatabaseField(columnName = "usn", canBeNull = false)
	private int usn;

	@DatabaseField(columnName = "ls", canBeNull = false)
	private int ls;

	@DatabaseField(columnName = "conf", canBeNull = false, width = 2000000000)
	private String conf;

	/**
	 * TODO: @matsu use custom data persister to serialize to and from Json
	 * using Jackson
	 */
	@DatabaseField(columnName = "models", canBeNull = false, persisterClass = JsonPersister.class)
	private Map<String, Model> models;

	@DatabaseField(columnName = "decks", canBeNull = false, width = 2000000000)
	private String decks;

	@DatabaseField(columnName = "dconf", canBeNull = false, width = 2000000000)
	private String dconf;

	@DatabaseField(columnName = "tags", canBeNull = false, width = 2000000000)
	private String tags;

	public Collection() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getCrt() {
		return this.crt;
	}

	public void setCrt(int crt) {
		this.crt = crt;
	}

	public int getMod() {
		return this.mod;
	}

	public void setMod(int mod) {
		this.mod = mod;
	}

	public int getScm() {
		return this.scm;
	}

	public void setScm(int scm) {
		this.scm = scm;
	}

	public int getVer() {
		return this.ver;
	}

	public void setVer(int ver) {
		this.ver = ver;
	}

	public int getDty() {
		return this.dty;
	}

	public void setDty(int dty) {
		this.dty = dty;
	}

	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	public int getLs() {
		return this.ls;
	}

	public void setLs(int ls) {
		this.ls = ls;
	}

	public String getConf() {
		return this.conf;
	}

	public void setConf(String conf) {
		this.conf = conf;
	}

	public Map<String, Model> getModels() {
		return this.models;
	}

	public void setModels(Map<String, Model> models) {
		this.models = models;
	}

	public String getDecks() {
		return this.decks;
	}

	public void setDecks(String decks) {
		this.decks = decks;
	}

	public String getDconf() {
		return this.dconf;
	}

	public void setDconf(String dconf) {
		this.dconf = dconf;
	}

	public String getTags() {
		return this.tags;
	}

	public void setTags(String tags) {
		this.tags = tags;
	}

}
