package com.rogueai.janki.core.persistence.entity;

// Generated 25-feb-2013 6.55.40 by Hibernate Tools 3.4.0.CR1

import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import com.rogueai.janki.core.persistence.dao.impl.GraveDao;

/**
 * Graves generated by hbm2java
 */
@DatabaseTable(tableName = "graves", daoClass = GraveDao.class)
public class Grave implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@DatabaseField(columnName = "usn", canBeNull = false)
	private int usn;
	@DatabaseField(columnName = "oid", canBeNull = false)
	private int oid;
	@DatabaseField(columnName = "type", canBeNull = false)
	private int type;

	public Grave(){
		super();
	}
	
	public Grave(int usn, int oid, int type) {
		this();
		this.usn = usn;
		this.oid = oid;
		this.type = type;
	}
	
	public int getUsn() {
		return this.usn;
	}

	public void setUsn(int usn) {
		this.usn = usn;
	}

	public int getOid() {
		return this.oid;
	}

	public void setOid(int oid) {
		this.oid = oid;
	}

	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
