/*
 * generated by Xtext
 */
package com.rogueai.janki.card.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CardTemplateRuntimeModule extends com.rogueai.janki.card.lang.AbstractCardTemplateRuntimeModule {

}
