/*
* generated by Xtext
*/
package com.rogueai.janki.card.lang;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CardTemplateStandaloneSetup extends CardTemplateStandaloneSetupGenerated{

	public static void doSetup() {
		new CardTemplateStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

