/*
 * generated by Xtext
 */
package com.rogueai.janki.card.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.rogueai.janki.card.lang.ui.internal.CardTemplateActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CardTemplateExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return CardTemplateActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return CardTemplateActivator.getInstance().getInjector(CardTemplateActivator.COM_ROGUEAI_JANKI_CARD_LANG_CARDTEMPLATE);
	}
	
}
