/*
* generated by Xtext
*/
package com.rogueai.janki.card.lang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.rogueai.janki.card.lang.services.CardTemplateGrammarAccess;

public class CardTemplateParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private CardTemplateGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.rogueai.janki.card.lang.parser.antlr.internal.InternalCardTemplateParser createParser(XtextTokenStream stream) {
		return new com.rogueai.janki.card.lang.parser.antlr.internal.InternalCardTemplateParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Html";
	}
	
	public CardTemplateGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(CardTemplateGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
